name: Docker Build and Push

on:
  push:
    branches:
      - main
  # release:
  #   types: [created]

env:
  APP_VERSION: ${{ github.event.release.tag_name }}
  DEVELOPER_HANDLE: ${{ github.repository_owner }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ env.DEVELOPER_HANDLE }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Swap Space
        uses: pierotofy/set-swap-space@v1.0
        with:
          swap-size-gb: 10
      - run: |
          # Workaround for https://github.com/rust-lang/cargo/issues/8719
          sudo mkdir -p /var/lib/docker
          sudo mount -t tmpfs -o size=10G none /var/lib/docker
          sudo systemctl restart docker

      - name: Build and push
        # if: github.event_name == 'release'
        run: |
          docker buildx build \
            --push \
            --platform linux/amd64 \
            --tag ghcr.io/${{ env.DEVELOPER_HANDLE }}/s5:amd64-${{ env.APP_VERSION }} \
            .

          docker buildx build \
            --push \
            --platform linux/arm/v7 \
            --tag ghcr.io/${{ env.DEVELOPER_HANDLE }}/s5:arm-v7-${{ env.APP_VERSION }} \
            .

          docker buildx build \
            --push \
            --platform linux/arm64/v8 \
            --tag ghcr.io/${{ env.DEVELOPER_HANDLE }}/s5:arm64-v8-${{ env.APP_VERSION }} \
            .

      - name: Create and push manifests
        # if: github.event_name == 'release'
        run: |
          # Export experimental CLI environment variable
          export DOCKER_CLI_EXPERIMENTAL=enabled

          # Create and push manifest for amd64 platform
          docker manifest create ghcr.io/${{ env.DEVELOPER_HANDLE }}/s5:${{ env.APP_VERSION }} \
            ghcr.io/${{ env.DEVELOPER_HANDLE }}/s5:amd64-${{ env.APP_VERSION }}
          docker manifest push ghcr.io/${{ env.DEVELOPER_HANDLE }}/s5:${{ env.APP_VERSION }}

          # Create and push manifest for arm-v7 platform
          docker manifest create ghcr.io/${{ env.DEVELOPER_HANDLE }}/s5:${{ env.APP_VERSION }} \
            ghcr.io/${{ env.DEVELOPER_HANDLE }}/s5:arm-v7-${{ env.APP_VERSION }} --amend
          docker manifest push ghcr.io/${{ env.DEVELOPER_HANDLE }}/s5:${{ env.APP_VERSION }}

          # Create and push manifest for arm64-v8 platform
          docker manifest create ghcr.io/${{ env.DEVELOPER_HANDLE }}/s5:${{ env.APP_VERSION }} \
            ghcr.io/${{ env.DEVELOPER_HANDLE }}/s5:arm64-v8-${{ env.APP_VERSION }} --amend
          docker manifest push ghcr.io/${{ env.DEVELOPER_HANDLE }}/s5:${{ env.APP_VERSION }}

      # # Saving this in case we ever want to start
      # - name: Test Build
      #   # if: github.event_name != 'release'
      #   run: |
      #     docker buildx build \
      #       --platform linux/amd64,linux/arm/v7,linux/arm64/v8 \
      #       .
