name: Docker Build and Push

on:
  push:
    branches:
      - "main"

env:
  APP_VERSION: 0.10.0

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        run: |
          docker buildx build \
            --push \
            --platform linux/amd64,linux/arm64 \
            --tag ghcr.io/lukehmcc/s5:latest \
            --tag ghcr.io/lukehmcc/s5:${{ env.APP_VERSION }} \
            .