name: Docker Build and Push

on:
  # push:
  #   branches:
  #     - main
  release:
    types: [created]

env:
  APP_VERSION: ${{ github.event.release.tag_name }}
  DEVELOPER_HANDLE: ${{ github.repository_owner }}
  LOCAL_BUILD: false

jobs:
  build-and-push-all-platforms:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to GitHub Container Registry
        if: env.LOCAL_BUILD != 'true'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ env.DEVELOPER_HANDLE }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Swap Space
        uses: pierotofy/set-swap-space@v1.0
        with:
          swap-size-gb: 10
      - run: |
          # Workaround for https://github.com/rust-lang/cargo/issues/8719
          sudo mkdir -p /var/lib/docker
          sudo mount -t tmpfs -o size=10G none /var/lib/docker
          sudo systemctl restart docker

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          images: |
            ghcr.io/${{ github.repository_owner }}/s5
          flavor: |
            latest=${{ startsWith(github.ref, 'refs/tags/') }}
          tags: type=ref,event=tag
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64, linux/arm64, linux/arm/v7
          build-args: |
            S5_DOCKER_TAG=${{ steps.meta.outputs.version }}
          push: true
          provenance: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}